# permissions for end users to edit migratingpods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: migratingpod-editor-role
rules:
- apiGroups:
  - podmig.schrej.net
  resources:
  - migratingpods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podmig.schrej.net
  resources:
  - migratingpods/status
  verbs:
  - get
