# permissions for end users to view migratingpods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: migratingpod-viewer-role
rules:
- apiGroups:
  - podmig.schrej.net
  resources:
  - migratingpods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - podmig.schrej.net
  resources:
  - migratingpods/status
  verbs:
  - get
