---
apiVersion: podmig.schrej.net/v1
kind: MigratingPod
metadata:
  name: network
  labels:
    scenario: network
spec:
  template:
    metadata:
      labels:
        scenario: network
    spec:
      containers:
      - name: redis
        image: redis
        ports:
          - containerPort: 6379
            protocol: TCP
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: network
spec:
  selector:
    scenario: network
  ports:
  - port: 6379
    targetPort: 6379